MOCK_RUNTIME_CONFIGS = {
    "legal_task": {
        "project_name": "legal_task",
        "version": "2026-04-07.1",
        "enabled": True,
        "metadata": {
            "description": "Legal monitoring workflow",
            "owner": "legal-team",
        },
        "agents": [
            {
                "agent_key": "title_screener",
                "role": "Legal News Title Screener",
                "goal": "Quickly screen article titles to identify potentially relevant legal news.",
                "backstory": "Pre-filters articles by title before expensive content analysis. Looks for legal keywords, policy changes, regulations, court decisions, and compliance topics.",
                "tools": [],
                "llm": "llama3.2:1b",
                "verbose": True,
                "allow_delegation": False,
                "enabled": True,
            },
            {
                "agent_key": "classifier",
                "role": "Legal News Classifier",
                "goal": "Classify legal articles by relevance, topic, and urgency based on full content.",
                "backstory": "Performs deep classification on pre-screened articles using full content analysis.",
                "tools": ["latest_news_link_crawler"],
                "llm": "llama3.2:1b",
                "verbose": True,
                "allow_delegation": False,
                "enabled": True,
            },
            {
                "agent_key": "reporter",
                "role": "Legal Report Writer",
                "goal": "Write concise legal reports from classified findings.",
                "backstory": "Summarizes legal developments into usable output.",
                "tools": [],
                "llm": "llama3.2:1b",
                "verbose": True,
                "allow_delegation": False,
                "enabled": True,
            },
            {
                "agent_key": "summary_translator",
                "role": "Legal Summary, Analysis And Translation Specialist",
                "goal": "Summarize and analyze relevant legal articles, then translate the summary, content, analysis, and recommendation into all target languages.",
                "backstory": "Creates concise summaries, analysis, and full multilingual outputs for legal monitoring across all required languages.",
                "tools": [],
                "llm": "llama3.2:1b",
                "verbose": True,
                "allow_delegation": False,
                "enabled": True,
            },
        ],
        "tasks": [
            {
                "task_key": "screen_titles",
                "description": "Review the list of article titles and select those that are potentially relevant to legal topics such as laws, regulations, decrees, court decisions, policies, and compliance. Return the list of relevant article URLs.",
                "expected_output": "A JSON list of article URLs that passed the title screening.",
                "agent_key": "title_screener",
                "context_task_keys": [],
                "output_key": "title_screening_result",
                "enabled": True,
            },
            {
                "task_key": "classify_articles",
                "description": "Classify the legal article by topic and urgency based on its full content.",
                "expected_output": "A structured classification result for the article.",
                "agent_key": "classifier",
                "context_task_keys": [],
                "output_key": "classification_result",
                "enabled": True,
            },
            {
                "task_key": "write_report",
                "description": "Write the final legal report from classified articles.",
                "expected_output": "A concise legal report for downstream users.",
                "agent_key": "reporter",
                "context_task_keys": ["classify_articles"],
                "output_key": "report_result",
                "enabled": True,
            },
            {
                "task_key": "summarize_article",
                "description": "Summarize the relevant legal article into a concise summary. Also provide an analysis of the legal implications and a recommended action.",
                "expected_output": "A summary, analysis, and recommendation for the legal article in the source language.",
                "agent_key": "summary_translator",
                "context_task_keys": [],
                "output_key": "summary_result",
                "enabled": True,
            },
            {
                "task_key": "translate_summary",
                "description": "Translate the summary, full article content, analysis, and recommendation into each target language. Each target language must have all four fields translated.",
                "expected_output": "A multilingual translation package with summary, content, analysis, and recommendation for each target language.",
                "agent_key": "summary_translator",
                "context_task_keys": ["summarize_article"],
                "output_key": "translation_result",
                "enabled": True,
            },
        ],
        "crews": [
            {
                "crew_key": "title_screening",
                "process": "sequential",
                "agent_keys": ["title_screener"],
                "task_keys": ["screen_titles"],
                "enabled": True,
            },
            {
                "crew_key": "classification",
                "process": "sequential",
                "agent_keys": ["classifier"],
                "task_keys": ["classify_articles"],
                "enabled": True,
            },
            {
                "crew_key": "reporting",
                "process": "sequential",
                "agent_keys": ["reporter"],
                "task_keys": ["write_report"],
                "enabled": True,
            },
            {
                "crew_key": "summary_translation",
                "process": "sequential",
                "agent_keys": ["summary_translator"],
                "task_keys": ["summarize_article", "translate_summary"],
                "enabled": True,
            },
        ],
    },
    "er_task": {
        "project_name": "er_task",
        "version": "2026-04-07.1",
        "enabled": True,
        "metadata": {
            "description": "ER monitoring workflow",
            "owner": "ops-team",
        },
        "agents": [
            {
                "agent_key": "classifier",
                "role": "ER News Classifier",
                "goal": "Classify ER articles by urgency, impact, and severity.",
                "backstory": "Screens emergency-response news for downstream workflows.",
                "tools": ["latest_news_link_crawler"],
                "llm": "llama3.2:1b",
                "verbose": True,
                "allow_delegation": False,
                "enabled": True,
            },
            {
                "agent_key": "reporter",
                "role": "ER Report Writer",
                "goal": "Write concise ER reports from classified findings.",
                "backstory": "Converts urgent article signals into operational output.",
                "tools": [],
                "llm": "llama3.2:1b",
                "verbose": True,
                "allow_delegation": False,
                "enabled": True,
            },
        ],
        "tasks": [
            {
                "task_key": "classify_articles",
                "description": "Classify crawled ER articles by urgency and severity.",
                "expected_output": "A structured classified list of ER articles.",
                "agent_key": "classifier",
                "context_task_keys": [],
                "output_key": "classification_result",
                "enabled": True,
            },
            {
                "task_key": "write_report",
                "description": "Write the final ER report from classified articles.",
                "expected_output": "A concise ER report for operations teams.",
                "agent_key": "reporter",
                "context_task_keys": ["classify_articles"],
                "output_key": "report_result",
                "enabled": True,
            },
        ],
        "crews": [
            {
                "crew_key": "classification",
                "process": "sequential",
                "agent_keys": ["classifier"],
                "task_keys": ["classify_articles"],
                "enabled": True,
            },
            {
                "crew_key": "reporting",
                "process": "sequential",
                "agent_keys": ["reporter"],
                "task_keys": ["write_report"],
                "enabled": True,
            },
        ],
    },
    "legal_task_report": {
        "project_name": "legal_task_report",
        "version": "2026-04-08.1",
        "enabled": True,
        "metadata": {
            "description": "Legal reporting workflow for summarized articles",
            "owner": "legal-team",
        },
        "agents": [
            {
                "agent_key": "reporter",
                "role": "Legal Report Writer",
                "goal": "Write concise legal reports from summarized legal findings.",
                "backstory": "Produces report outputs from already processed legal articles.",
                "tools": [],
                "llm": "llama3.2:1b",
                "verbose": True,
                "allow_delegation": False,
                "enabled": True,
            }
        ],
        "tasks": [
            {
                "task_key": "write_report",
                "description": "Write the final legal report from the provided summary, translations, and classification result.",
                "expected_output": "A concise legal report for downstream users.",
                "agent_key": "reporter",
                "context_task_keys": [],
                "output_key": "report_result",
                "enabled": True,
            }
        ],
        "crews": [
            {
                "crew_key": "reporting",
                "process": "sequential",
                "agent_keys": ["reporter"],
                "task_keys": ["write_report"],
                "enabled": True,
            }
        ],
    },
}
