MOCK_RUNTIME_CONFIGS = {
    "legal_task": {
        "project_name": "legal_task",
        "version": "2026-04-07.1",
        "enabled": True,
        "metadata": {
            "description": "Legal monitoring workflow",
            "owner": "legal-team",
        },
        "agents": [
            {
                "agent_key": "classifier",
                "role": "Legal News Classifier",
                "goal": "Classify legal articles by relevance, topic, and urgency.",
                "backstory": "Triages legal news for downstream processing.",
                "tools": ["latest_news_link_crawler"],
                "llm": "llama3.2:1b",
                "verbose": True,
                "allow_delegation": False,
                "enabled": True,
            },
            {
                "agent_key": "reporter",
                "role": "Legal Report Writer",
                "goal": "Write concise legal reports from classified findings.",
                "backstory": "Summarizes legal developments into usable output.",
                "tools": [],
                "llm": "llama3.2:1b",
                "verbose": True,
                "allow_delegation": False,
                "enabled": True,
            },
            {
                "agent_key": "summary_translator",
                "role": "Legal Summary And Translation Specialist",
                "goal": "Summarize relevant legal articles and translate the summary into target languages.",
                "backstory": "Creates concise summaries and multilingual outputs for legal monitoring.",
                "tools": [],
                "llm": "llama3.2:1b",
                "verbose": True,
                "allow_delegation": False,
                "enabled": True,
            },
        ],
        "tasks": [
            {
                "task_key": "classify_articles",
                "description": "Classify crawled legal articles by topic and urgency.",
                "expected_output": "A structured classified list of legal articles.",
                "agent_key": "classifier",
                "context_task_keys": [],
                "output_key": "classification_result",
                "enabled": True,
            },
            {
                "task_key": "write_report",
                "description": "Write the final legal report from classified articles.",
                "expected_output": "A concise legal report for downstream users.",
                "agent_key": "reporter",
                "context_task_keys": ["classify_articles"],
                "output_key": "report_result",
                "enabled": True,
            },
            {
                "task_key": "summarize_article",
                "description": "Summarize the relevant legal article into a concise, accurate summary.",
                "expected_output": "A short summary of the legal article.",
                "agent_key": "summary_translator",
                "context_task_keys": [],
                "output_key": "summary_result",
                "enabled": True,
            },
            {
                "task_key": "translate_summary",
                "description": "Translate the generated summary into two target languages chosen from Korean, English, and Vietnamese.",
                "expected_output": "A multilingual translation package for the summary.",
                "agent_key": "summary_translator",
                "context_task_keys": ["summarize_article"],
                "output_key": "translation_result",
                "enabled": True,
            },
        ],
        "crews": [
            {
                "crew_key": "classification",
                "process": "sequential",
                "agent_keys": ["classifier"],
                "task_keys": ["classify_articles"],
                "enabled": True,
            },
            {
                "crew_key": "reporting",
                "process": "sequential",
                "agent_keys": ["reporter"],
                "task_keys": ["write_report"],
                "enabled": True,
            },
            {
                "crew_key": "summary_translation",
                "process": "sequential",
                "agent_keys": ["summary_translator"],
                "task_keys": ["summarize_article", "translate_summary"],
                "enabled": True,
            },
        ],
    },
    "er_task": {
        "project_name": "er_task",
        "version": "2026-04-07.1",
        "enabled": True,
        "metadata": {
            "description": "ER monitoring workflow",
            "owner": "ops-team",
        },
        "agents": [
            {
                "agent_key": "classifier",
                "role": "ER News Classifier",
                "goal": "Classify ER articles by urgency, impact, and severity.",
                "backstory": "Screens emergency-response news for downstream workflows.",
                "tools": ["latest_news_link_crawler"],
                "llm": "llama3.2:1b",
                "verbose": True,
                "allow_delegation": False,
                "enabled": True,
            },
            {
                "agent_key": "reporter",
                "role": "ER Report Writer",
                "goal": "Write concise ER reports from classified findings.",
                "backstory": "Converts urgent article signals into operational output.",
                "tools": [],
                "llm": "llama3.2:1b",
                "verbose": True,
                "allow_delegation": False,
                "enabled": True,
            },
        ],
        "tasks": [
            {
                "task_key": "classify_articles",
                "description": "Classify crawled ER articles by urgency and severity.",
                "expected_output": "A structured classified list of ER articles.",
                "agent_key": "classifier",
                "context_task_keys": [],
                "output_key": "classification_result",
                "enabled": True,
            },
            {
                "task_key": "write_report",
                "description": "Write the final ER report from classified articles.",
                "expected_output": "A concise ER report for operations teams.",
                "agent_key": "reporter",
                "context_task_keys": ["classify_articles"],
                "output_key": "report_result",
                "enabled": True,
            },
        ],
        "crews": [
            {
                "crew_key": "classification",
                "process": "sequential",
                "agent_keys": ["classifier"],
                "task_keys": ["classify_articles"],
                "enabled": True,
            },
            {
                "crew_key": "reporting",
                "process": "sequential",
                "agent_keys": ["reporter"],
                "task_keys": ["write_report"],
                "enabled": True,
            },
        ],
    },
    "legal_task_report": {
        "project_name": "legal_task_report",
        "version": "2026-04-08.1",
        "enabled": True,
        "metadata": {
            "description": "Legal reporting workflow for summarized articles",
            "owner": "legal-team",
        },
        "agents": [
            {
                "agent_key": "reporter",
                "role": "Legal Report Writer",
                "goal": "Write concise legal reports from summarized legal findings.",
                "backstory": "Produces report outputs from already processed legal articles.",
                "tools": [],
                "llm": "llama3.2:1b",
                "verbose": True,
                "allow_delegation": False,
                "enabled": True,
            }
        ],
        "tasks": [
            {
                "task_key": "write_report",
                "description": "Write the final legal report from the provided summary, translations, and classification result.",
                "expected_output": "A concise legal report for downstream users.",
                "agent_key": "reporter",
                "context_task_keys": [],
                "output_key": "report_result",
                "enabled": True,
            }
        ],
        "crews": [
            {
                "crew_key": "reporting",
                "process": "sequential",
                "agent_keys": ["reporter"],
                "task_keys": ["write_report"],
                "enabled": True,
            }
        ],
    },
}
