const MockData = {
    projects: [
        {
            project_name: 'legal_task',
            version: '2026-04-07.1',
            enabled: true,
            require_approval: true,
            run_status: 'idle',
            metadata: { description: 'Legal monitoring workflow', owner: 'legal-team' },
        },
        {
            project_name: 'er_task',
            version: '2026-04-07.1',
            enabled: true,
            require_approval: false,
            run_status: 'running',
            metadata: { description: 'ER monitoring workflow', owner: 'ops-team' },
        },
        {
            project_name: 'legal_task_report',
            version: '2026-04-08.1',
            enabled: true,
            require_approval: false,
            run_status: 'idle',
            metadata: { description: 'Legal reporting workflow', owner: 'legal-team' },
        },
    ],

    agents: {
        legal_task: [
            { agent_key: 'title_screener', role: 'Legal News Title Screener',
              goal: 'Quickly screen article titles to identify potentially relevant legal news.',
              backstory: 'Pre-filters articles by title before expensive content analysis.',
              tools: [], llm: 'openrouter/google/gemini-2.0-flash-exp:free',
              verbose: true, allow_delegation: false, enabled: true },
            { agent_key: 'classifier', role: 'Legal News Classifier',
              goal: 'Classify legal articles by relevance, topic, and urgency.',
              backstory: 'Performs deep classification on pre-screened articles.',
              tools: [], llm: 'openrouter/google/gemini-2.0-flash-exp:free',
              verbose: true, allow_delegation: false, enabled: true },
            { agent_key: 'summary', role: 'Article Summarizer',
              goal: 'Read the article and produce a concise summary, analysis, and recommendation.',
              backstory: 'Expert at reading news articles and extracting key information.',
              tools: [], llm: 'openrouter/google/gemini-2.0-flash-exp:free',
              verbose: true, allow_delegation: false, enabled: true },
            { agent_key: 'translator', role: 'Article Translator',
              goal: 'Translate title, summary, content, analysis, recommendation into target language.',
              backstory: 'Professional translator, always returns JSON with 5 keys.',
              tools: [], llm: 'openrouter/google/gemini-2.0-flash-exp:free',
              verbose: true, allow_delegation: false, enabled: true },
        ],
        er_task: [
            { agent_key: 'classifier', role: 'ER News Classifier',
              goal: 'Classify ER articles by urgency, impact, and severity.',
              backstory: 'Screens emergency-response news.',
              tools: [], llm: 'ollama/llama3.2:1b',
              verbose: true, allow_delegation: false, enabled: true },
            { agent_key: 'reporter', role: 'ER Report Writer',
              goal: 'Write concise ER reports.',
              backstory: 'Converts urgent article signals into operational output.',
              tools: [], llm: 'ollama/llama3.2:1b',
              verbose: true, allow_delegation: false, enabled: true },
        ],
        legal_task_report: [
            { agent_key: 'reporter', role: 'Legal Report Writer',
              goal: 'Write legal reports from summarized findings.',
              backstory: 'Produces report outputs.',
              tools: [], llm: 'openai/gpt-4o-mini',
              verbose: true, allow_delegation: false, enabled: true },
        ],
    },

    tasks: {
        legal_task: [
            { task_key: 'screen_titles', agent_key: 'title_screener',
              description: 'Review article titles and select those relevant to legal topics.',
              expected_output: 'A JSON list of article URLs that passed screening.',
              context_task_keys: [], output_key: 'title_screening_result', enabled: true },
            { task_key: 'classify_articles', agent_key: 'classifier',
              description: 'Classify the legal article by topic and urgency based on full content.',
              expected_output: 'A structured classification result.',
              context_task_keys: [], output_key: 'classification_result', enabled: true },
            { task_key: 'summarize_article', agent_key: 'summary',
              description: 'Read article and return JSON with title, summary, analysis, recommendation in {source_language}.',
              expected_output: 'JSON: {title, summary, analysis, recommendation}',
              context_task_keys: [], output_key: 'summary_result', enabled: true },
            { task_key: 'translate_summary', agent_key: 'translator',
              description: 'Translate title, summary, content, analysis, recommendation from {source_language} to {target_language}.',
              expected_output: 'JSON: {title, summary, content, analysis, recommendation}',
              context_task_keys: [], output_key: 'translation_result', enabled: true },
            { task_key: 'write_report', agent_key: 'classifier',
              description: 'Write final legal report from classified articles.',
              expected_output: 'A concise legal report.',
              context_task_keys: ['classify_articles'], output_key: 'report_result', enabled: false },
        ],
        er_task: [
            { task_key: 'classify_articles', agent_key: 'classifier',
              description: 'Classify crawled ER articles by urgency and severity.',
              expected_output: 'A structured classified list.',
              context_task_keys: [], output_key: 'classification_result', enabled: true },
            { task_key: 'write_report', agent_key: 'reporter',
              description: 'Write the final ER report.',
              expected_output: 'A concise ER report.',
              context_task_keys: ['classify_articles'], output_key: 'report_result', enabled: true },
        ],
        legal_task_report: [
            { task_key: 'write_report', agent_key: 'reporter',
              description: 'Write the final legal report from summary and translations.',
              expected_output: 'A concise legal report.',
              context_task_keys: [], output_key: 'report_result', enabled: true },
        ],
    },

    emails: {
        legal_task: [
            { id: 1, task_key: 'classify_articles', email: 'legal@company.com',
              name: 'Legal Team', recipient_type: 'department', enabled: true },
            { id: 2, task_key: 'classify_articles', email: 'admin@company.com',
              name: 'Admin', recipient_type: 'user', enabled: true },
            { id: 3, task_key: 'summarize_article', email: 'compliance-group@company.com',
              name: 'Compliance Group', recipient_type: 'group', enabled: true },
            { id: 4, task_key: 'translate_summary', email: 'translator@company.com',
              name: 'Translator', recipient_type: 'user', enabled: true },
        ],
        er_task: [
            { id: 5, task_key: 'write_report', email: 'ops@company.com',
              name: 'Ops Team', recipient_type: 'department', enabled: true },
        ],
        legal_task_report: [],
    },

    access: {
        legal_task: [
            { id: 1, email: 'admin@company.com', name: 'Admin User', role: 'admin', granted_at: '2026-04-01 10:00:00' },
            { id: 2, email: 'legal-manager@company.com', name: 'Legal Manager', role: 'editor', granted_at: '2026-04-05 14:30:00' },
            { id: 3, email: 'analyst@company.com', name: 'Analyst', role: 'viewer', granted_at: '2026-04-10 09:15:00' },
        ],
        er_task: [
            { id: 4, email: 'ops-lead@company.com', name: 'Ops Lead', role: 'admin', granted_at: '2026-04-02 11:00:00' },
        ],
        legal_task_report: [],
    },

    sources: [
        { site_id: 'tn-legal-1', name: 'Bao Thanh Nien', domain: 'thanhnien.vn',
          project_name: 'legal_task', language: 'vi', fetch_method: 'sitemap', active: true },
        { site_id: 'dt-legal-1', name: 'Bao Dan Tri', domain: 'dantri.com.vn',
          project_name: 'legal_task', language: 'vi', fetch_method: 'listing', active: true },
        { site_id: 'vnx-er-1', name: 'VnExpress', domain: 'vnexpress.net',
          project_name: 'er_task', language: 'vi', fetch_method: 'sitemap', active: false },
    ],

    schedulers: [
        { job_id: 'legal_task_ingest', project_name: 'legal_task',
          trigger_type: 'cron', trigger_args: { hour: '0,6,12', minute: 0 },
          enabled: true, timezone: 'Asia/Ho_Chi_Minh' },
        { job_id: 'legal_task_report_14h', project_name: 'legal_task_report',
          trigger_type: 'cron', trigger_args: { hour: 14, minute: 0 },
          enabled: true, timezone: 'Asia/Ho_Chi_Minh' },
        { job_id: 'er_task_every_15m', project_name: 'er_task',
          trigger_type: 'cron', trigger_args: { minute: '*/15' },
          enabled: true, timezone: 'Asia/Ho_Chi_Minh' },
    ],

    articles: [
        { id: 1, title: 'Quốc hội thông qua Luật Đất đai sửa đổi', project_name: 'legal_task',
          relevance_score: 92, is_relevant: true, published_at_vn: '15/04/2026 08:30 ICT' },
        { id: 2, title: 'Chính phủ ban hành nghị định mới về thuế', project_name: 'legal_task',
          relevance_score: 85, is_relevant: true, published_at_vn: '15/04/2026 10:15 ICT' },
        { id: 3, title: 'Giá vàng tăng mạnh', project_name: 'legal_task',
          relevance_score: 20, is_relevant: false, published_at_vn: '15/04/2026 11:00 ICT' },
        { id: 4, title: 'Cháy lớn tại khu công nghiệp', project_name: 'er_task',
          relevance_score: 95, is_relevant: true, published_at_vn: '15/04/2026 13:45 ICT' },
        { id: 5, title: 'Dự báo thời tiết', project_name: 'er_task',
          relevance_score: 30, is_relevant: false, published_at_vn: '15/04/2026 14:00 ICT' },
    ],
};
